name: Release
on:
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
        with:
          role_name: "arn:aws:iam::${{ secrets.SECRETS_ACCOUNT_ID }}:role/gh-semantic-release-secrets-read-access"
          app_name: "semantic-release-config"
          step_name: "Release"
          secret_prefix: "NPM"
          secret_name: "arn:aws:secretsmanager:eu-west-2:${{ secrets.SECRETS_ACCOUNT_ID }}:secret:github-actions/radixdlt/semantic-release-config/npm_token-csk6kI"
          parse_json: true

      - name: Checkout
        uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: RDXWorks-actions/setup-node@main
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release | tee out
          echo "RELEASE_VERSION=$(grep 'Created tag ' out | awk -F 'Created tag ' '{print $2}')" >> $GITHUB_ENV
